In [1]:
import dgl
import numpy as np
import torch

Using backend: pytorch


In [2]:
# Objective
# 1. Construct a graph in DGL from scratch
# 2. Assign node and edge features to a graph
# 3. Query properties of a DGL graph such as node degrees and connectivity
# 4. Transform a DGL graph into another graph
# 5. Load and save DGL graphs

In [8]:
# 1. Construct a graph in DGL from scratch --> source_nodes --> destination nodes
g = dgl.graph(([0,0,0,0,0], [1,2,3,4,5]), num_nodes=6) 
# pytorch LongTensors also works 
# dgl.graph((torch.LongTensor([0, 0, 0, 0, 0]), torch.LongTensor([1, 2, 3, 4, 5])), num_nodes=6)
# dgl.graph((torch.LongTensor([0, 0, 0, 0, 0]), torch.LongTensor([1, 2, 3, 4, 5]))
print('nodes: ', g.nodes())
print('edges: ', g.edges())

nodes:  tensor([0, 1, 2, 3, 4, 5])
edges:  (tensor([0, 0, 0, 0, 0]), tensor([1, 2, 3, 4, 5]))


In [12]:
# Assign a 3-d node feature vector for each node
g.ndata['x'] = torch.randn(6,3)
# Assign a 4-d edge feature vector for each edge
g.edata['a'] = torch.randn(5,4)
# Assign a 5x4 node feature matrix for each node. Node and edge features in DGL can be multi-dimensional
g.ndata['y'] = torch.randn(6,5,4)


In [22]:
# Induce a subgraph from node 0, node 1 and node 3 from the original graph
sg1 = g.subgraph([0, 1, 3])

# Induce subgraph from edge 0, edge 1, and edge 3 from the original graph
sg2 = g.edge_subgraph([0, 1, 3])

In [25]:
# The original IDs of each node in sg1
print(sg1.ndata[dgl.NID])
# The original IDs of each edge in sg1
print(sg1.ndata[dgl.EID])

tensor([0, 1, 3])
tensor([0, 1, 3])


In [26]:
# The original IDs of each node in sg2
print(sg2.ndata[dgl.NID])
# The original IDs of each edge in sg2
print(sg2.edata[dgl.EID])

tensor([0, 1, 2, 4])
tensor([0, 1, 3])


In [27]:
# The original node feature of each node in sg1
print(sg1.ndata['x'])
# The original edge feature of each node in sg1
print(sg1.edata['a'])
# The original node feature of each node in sg2
print(sg2.ndata['x'])
# The original edge feature of each node in sg2
print(sg2.edata['a'])

tensor([[-0.5014,  0.0623, -0.1747],
        [ 0.5655,  0.8478, -0.1648],
        [ 0.1427,  1.1246,  1.1225]])
tensor([[ 0.8113, -0.8511,  1.1330,  0.9474],
        [ 0.2626, -1.2309, -0.3946, -0.6059]])
tensor([[-0.5014,  0.0623, -0.1747],
        [ 0.5655,  0.8478, -0.1648],
        [ 0.7736, -0.0905,  0.2630],
        [-0.5171,  1.8167,  0.6844]])
tensor([[ 0.8113, -0.8511,  1.1330,  0.9474],
        [ 1.4226, -3.0010, -2.0849,  0.4687],
        [ 0.3475,  1.3411,  0.0846,  0.5755]])


In [28]:
# For undirected graph, convert into a bidirectional graph first by add reverse edges
newg = dgl.add_reverse_edges(g)
newg.edges()

(tensor([0, 0, 0, 0, 0, 1, 2, 3, 4, 5]),
 tensor([1, 2, 3, 4, 5, 0, 0, 0, 0, 0]))

In [30]:
# Save graphs
dgl.save_graphs('graph.dgl', g)
dgl.save_graphs('graphs.dgl', [g, sg1, sg2])

In [32]:
# Load graphs
(g,), _ = dgl.load_graphs('graph.dgl')
print(g)

(g, sg1, sg2), _ = dgl.load_graphs('graphs.dgl')
print(g)
print(sg1)
print(sg2)

Graph(num_nodes=6, num_edges=5,
      ndata_schemes={'y': Scheme(shape=(5, 4), dtype=torch.float32), 'x': Scheme(shape=(3,), dtype=torch.float32)}
      edata_schemes={'a': Scheme(shape=(4,), dtype=torch.float32)})
Graph(num_nodes=6, num_edges=5,
      ndata_schemes={'y': Scheme(shape=(5, 4), dtype=torch.float32), 'x': Scheme(shape=(3,), dtype=torch.float32)}
      edata_schemes={'a': Scheme(shape=(4,), dtype=torch.float32)})
Graph(num_nodes=3, num_edges=2,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(5, 4), dtype=torch.float32)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'a': Scheme(shape=(4,), dtype=torch.float32)})
Graph(num_nodes=4, num_edges=3,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(5, 4), dtype=torch.float32)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'a': Scheme